#pragma once

// file type
typedef enum _FILETYPE_ {
	FILETYPE_SCRIPT,
	FILETYPE_TEXT,
	FILETYPE_README,
	FILETYPE_MAP,
	FILETYPE_MOD,
	FILETYPE_UNINSTALL,
	FILETYPE_SOUND,
	FILETYPE_EXTRA,
	FILETYPE_SCREEN,
	FILETYPE_MISSION,
	FILETYPE_ADVERT,
	FILETYPE_SHIPOTHER,
	FILETYPE_SHIPMODEL,
	FILETYPE_SHIPSCENE,
	FILETYPE_COCKPITSCENE,
	FILETYPE_SOUNDTRACK,
	FILETYPE_MAX,
	FILETYPE_BACKUP,
	FILETYPE_UNKNOWN = -1
} FileType;
